name: Build

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout du code source
      uses: actions/checkout@v2

    - name: Install NASM
      run: sudo apt-get update && sudo apt-get install -y nasm

    - name: Compile
      run: make compile
